import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Advent_Pro } from "next/font/google";
import ThemeProvider from "@/components/main/ThemeProvider";
import CookieWrapper from "@/components/main/CookieWrapper";
import { Toaster } from "@/components/ui/toaster";

const ap = Advent_Pro({ subsets: ["latin"], weight: "700" });

export const metadata: Metadata = {
  title: "Parsa Airline Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ap.className}>
        <CookieWrapper>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <div className="flex flex-row justify-between items-center w-full h-full min-h-[100vh]">
              <Navbar />
              <div className="flex-1 w-[20%]">&nbsp;</div>
              <div className="flex-4 w-[80%] flex flex-col justify-between items-start min-h-[100vh]">
                {children}
                <Footer />
              </div>
            </div>
            <Toaster />
          </ThemeProvider>
        </CookieWrapper>
      </body>
    </html>
  );
}
